Repository Paciente8159/uCNC-modules, pull requests merged in 2024-08, with the labels that each got.

#54 initial release of a touch release module
  touch_screen/CHANGELOG.md
  touch_screen/README.md
  touch_screen/touch_screen.c
  touch_screen/touch_screen.h
Labels: new module, new feature: module

#57 v11000 display module update
  graphic_display/graphic_display.c
  graphic_display/graphic_display.h
  graphic_display/graphic_display_u8g2.c
Labels: enhancement

#58 Updated SD Card v2 module to v11000
  sd_card_v2/diskio.c
  sd_card_v2/diskio.h
  sd_card_v2/fat_fs/ffconf.h
  sd_card_v2/sd_card_v2.c
  sd_card_v2/sd_messages.h
Labels: enhancement

#60 TFT display module
  tft_display/CHANGELOG.md
  tft_display/README.md
  tft_display/driver.h
  tft_display/driver/ILI9486.h
  tft_display/tft_display.c
  tft_display/tft_display.h
Labels: new module, new feature: module

#59 LVGL module
  lvgl/CHANGELOG.md
  lvgl/README.md
  lvgl/lv_conf.h
  lvgl/lvgl_support.c
  lvgl/lvgl_support.h
  lvgl/style/config.h
  lvgl/style/style.h
  lvgl/style/win9x/bitmaps/checkbox.h
  lvgl/style/win9x/bitmaps/close.h
  lvgl/style/win9x/bitmaps/lock.h
  lvgl/style/win9x/bitmaps/logo.h
  lvgl/style/win9x/bitmaps/menu.h
  lvgl/style/win9x/bitmaps/move.h
  lvgl/style/win9x/bitmaps/warning.h
  lvgl/style/win9x/bitmaps/zero.h
  lvgl/style/win9x/colors.h
  lvgl/style/win9x/config.h
  lvgl/style/win9x/elements.c
  lvgl/style/win9x/elements.h
  lvgl/style/win9x/fonts/pixel.h
  lvgl/style/win9x/fonts/pixel_14pt.c
  lvgl/style/win9x/fonts/pixel_7pt.c
  lvgl/style/win9x/fonts/pixel_bold_11pt.c
  lvgl/style/win9x/fonts/pixel_mono.h
  lvgl/style/win9x/fonts/pixel_mono_14pt.c
  lvgl/style/win9x/fonts/pixel_mono_7pt.c
  lvgl/style/win9x/main.c
  lvgl/style/win9x/screens/idle.c
  lvgl/style/win9x/screens/list_menu.c
  lvgl/style/win9x/screens/movement.c
  lvgl/style/win9x/screens/popup.c
  lvgl/style/win9x/screens/startup.c
  lvgl/style/win9x/styles.h
Labels: new module, new feature: module

#63 fixed touch screen rotation
  touch_screen/CHANGELOG.md
  touch_screen/touch_screen.c
  touch_screen/touch_screen.h
Labels: bug, enhancement

#62 added support for touch screen on tft display
  tft_display/CHANGELOG.md
  tft_display/README.md
  tft_display/tft_display.c
Labels: enhancement

#69 updated pin range in extra MCodes
  M42/CHANGELOG.md
  M42/parser_m42.c
  M62-M65/CHANGELOG.md
  M62-M65/parser_m62_m65.c
Labels: enhancement

#70 fixes on mks display and touch modules
  mks_display/lv_conf.h
  mks_display/mks_display.c
  touch_screen/touch_screen.c
Labels: bug, enhancement, needs: testing

#71 fixed web pendant stream buffer enqueue
  web_pendant/CHANGELOG.md
  web_pendant/web_pendant.c
Labels: bug
